services:
  live:
    image: ghcr.io/slowlydev/f1-dash-live:latest
    build:
      context: .
      target: live
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      - ORIGIN=https://livetiming.formulacritica.it
      - LIVE_ADDRESS=0.0.0.0:4000
      - RUST_LOG=live=info

  api:
    image: ghcr.io/slowlydev/f1-dash-api:latest
    build:
      context: .
      target: api
    restart: unless-stopped
    ports:
      - 4001:4001
    environment:
      - ORIGIN=https://livetiming.formulacritica.it
      - API_ADDRESS=0.0.0.0:4001
      - RUST_LOG=api=info

  frontend:
    image: ghcr.io/slowlydev/f1-dash:latest
    build:
      context: ./dash/
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - api
      - live
    environment:
      - NEXT_PUBLIC_LIVE_URL=https://livetiming.formulacritica.it
      - API_URL=https://livetiming.formulacritica.it/api
      - DISABLE_IFRAME=0

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password

  importer:
    image: ghcr.io/slowlydev/f1-dash-importer:latest
    build:
      context: .
      target: importer
    environment:
      - DATABASE_URL=postgres://postgres:password@timescaledb:5432/postgres

  analytics:
    image: ghcr.io/slowlydev/f1-dash-analytics:latest
    build:
      context: .
      target: analytics
    environment:
      - ORIGIN=https://livetiming.formulacritica.it
      - ANALYTICS_ADDRESS=0.0.0.0:4002
      - RUST_LOG=analytics=info
